name: monitor_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pyarrow
  - python=3.12
  - numpy
  - matplotlib
  - pandas
  - redis
  - tqdm
  - typing_extensions
  - pip
  - pip:
    - MetaTrader5
    - watchdog
    - pika