-- Create the ticks table for MT5 tick data
-- This table will store tick data from MetaTrader 5
CREATE TABLE ticks (
  symbol Enum8(
    'ADAUSD' = 1,
    'AUDCAD' = 2,
    'AUDCHF' = 3,
    'AUDJPY' = 4,
    'AUDNZD' = 5,
    'AUDUSD' = 6,
    'AUS200' = 7,
    'AVXUSD' = 8,
    'BCHUSD' = 9,
    'BNBUSD' = 10,
    'BTCUSD' = 11,
    'CADCHF' = 12,
    'CADJPY' = 13,
    'CHFJPY' = 14,
    'DE40' = 15,
    'DOGUSD' = 16,
    'DOTUSD' = 17,
    'DXY_Z5' = 18,
    'ETHUSD' = 19,
    'EURAUD' = 20,
    'EURCAD' = 21,
    'EURCHF' = 22,
    'EURGBP' = 23,
    'EURJPY' = 24,
    'EURNZD' = 25,
    'EURUSD' = 26,
    'F40' = 27,
    'GBPAUD' = 28,
    'GBPCAD' = 29,
    'GBPCHF' = 30,
    'GBPJPY' = 31,
    'GBPNZD' = 32,
    'GBPUSD' = 33,
    'JP225' = 34,
    'LNKUSD' = 35,
    'NZDCAD' = 36,
    'NZDCHF' = 37,
    'NZDJPY' = 38,
    'NZDUSD' = 39,
    'SOLUSD' = 40,
    'STOXX50' = 41,
    'UK100' = 42,
    'US30' = 43,
    'US500' = 44,
    'USDCAD' = 45,
    'USDCHF' = 46,
    'USDJPY' = 47,
    'USDSGD' = 48,
    'USTEC' = 49,
    'XAGAUD' = 50,
    'XAGEUR' = 51,
    'XAGUSD' = 52,
    'XAUAUD' = 53,
    'XAUCHF' = 54,
    'XAUEUR' = 55,
    'XAUGBP' = 56,
    'XAUJPY' = 57,
    'XAUUSD' = 58,
    'XLMUSD' = 59,
    'XPTUSD' = 60,
    'XRPUSD' = 61,
    'XTZUSD' = 62,
    'LTCUSD' = 63,
    'XPDUSD' = 64
  ) CODEC(LZ4),
  time   DateTime64(3)          CODEC(DoubleDelta, LZ4),
  bid    Float32                CODEC(Gorilla, ZSTD(3)),
  ask    Float32                CODEC(Gorilla, ZSTD(3))
)
ENGINE = ReplacingMergeTree()
PARTITION BY toYYYYMMDD(time)
ORDER BY (symbol, time);
